package dev.amal.borutoapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val DEFAULT_PADDING = 12.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp
val SUPER_EXTRA_SMALL_PADDING = 3.dp

val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp

val TOP_APP_BAR_HEIGHT = 56.dp
val HERO_ITEM_HEIGHT = 500.dp
val NAME_PLACEHOLDER_HEIGHT = 30.dp
val ABOUT_PLACEHOLDER_HEIGHT = 15.dp
val RATING_PLACEHOLDER_HEIGHT = 20.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp

val DEFAULT_ICON_SIZE = 32.dp

val MIN_SHEET_HEIGHT = 140.dp
const val MIN_BACKGROUND_IMAGE_HEIGHT = 0.5f